package com.hd.mapper;

import com.hd.model.Userbean;

public interface UserbeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    int insert(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    int insertSelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    Userbean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    int updateByPrimaryKeySelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Tue May 09 20:42:40 CST 2017
     */
    int updateByPrimaryKey(Userbean record);
}